# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins_dir:
  - octopress-autoprefixer

# Site settings
title: Make it happen ...
email: ginale7(at)gmail(dot)com
description: > # this means to ignore newlines until "baseurl:"
 &copy; 2017 gingeryale
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gingeryale
behance_username: gingeryale1429


# Build settings
markdown: kramdown
