# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
gems:
  - octopress-autoprefixer

# Site settings
title: Make it happen ...
email: gingeryale7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Thanks for stopping by my site. If you liked what you saw, get in touch!
 I'm available for hire as a fulltime or part time freelance or steady position
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gingeryale

# Build settings
markdown: kramdown
