# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins_dir:
  - octopress-autoprefixer

# Site settings
title: Make it happen ...
email: "&#103;&#105;&#110;&#097;&#108;&#101;&#055;&#064;&#103;&#109;&#120;&#046;&#099;&#111;&#109;"
description: > # this means to ignore newlines until "baseurl:"
 &copy; 2017 gingeryale
baseurl: "/greeting" # the subpath of your site, e.g. /blog /greeting
url: "http://gingeryale.github.io" # the base hostname & protocol for your site 
twitter_username: _ttwwa
github_username:  gingeryale
behance_username: gingeryale


# Build settings
markdown: kramdown
